### PR TITLE
Request to add new rules

### PR DESCRIPTION
**Pull request by PauMacasaet**
Rules added:

**detect-improper-exception-handling** [(link)](https://cheatsheetseries.owasp.org/cheatsheets/Nodejs_Security_Cheat_Sheet.html#handle-uncaughtexception)

**detect-unhandled-async-errors** [(link)](https://cheatsheetseries.owasp.org/cheatsheets/Nodejs_Security_Cheat_Sheet.html#handle-errors-in-asynchronous-calls)

**detect-unhandled-event-errors** [(link)](https://cheatsheetseries.owasp.org/cheatsheets/Nodejs_Security_Cheat_Sheet.html#listen-to-errors-when-using-eventemitter)

### CODE REVIEW

**Comment by gkouziik** [comment]
I will review the new rules as soon as possible. Again my apologies for my late response
Thanks in advance for your contribution @PauMacasaet

**Comment by PauMacasaet** [comment]
Sure thing! Thank you also.

**Comment by PauMacasaet** [comment]
I added some revisions for false detections on some of the rules newly created

**Comment by gkouziik** [comment]
> I added some revisions for false detections on some of the rules newly created

Thanks for you contribution, the updated version is published on **npm**

**Comment by PauMacasaet** [comment]
Thank you also!

**Pull request merged**
